[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore:codecs\.open\(\) is deprecated:DeprecationWarning:pypinyin\..*
    ignore:could not create cache path.*:pytest.PytestCacheWarning
    ignore:Exception ignored while calling deallocator.*:pytest.PytestUnraisableExceptionWarning
